import { InspirationQuote } from '@/types';

export const leadershipQuotes: Omit<InspirationQuote, 'id'>[] = [
  {
    week_number: 1,
    quote_text: "A leader is one who knows the way, goes the way, and shows the way.",
    author: "John C. Maxwell",
    category: "Leadership",
  },
  {
    week_number: 2,
    quote_text: "The function of leadership is to produce more leaders, not more followers.",
    author: "Ralph Nader",
    category: "Leadership",
  },
  {
    week_number: 3,
    quote_text: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    category: "Innovation",
  },
  {
    week_number: 4,
    quote_text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.",
    author: "Ronald Reagan",
    category: "Leadership",
  },
  {
    week_number: 5,
    quote_text: "Leadership is the capacity to translate vision into reality.",
    author: "Warren Bennis",
    category: "Leadership",
  },
  {
    week_number: 6,
    quote_text: "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.",
    author: "Jack Welch",
    category: "Leadership",
  },
  {
    week_number: 7,
    quote_text: "The quality of a leader is reflected in the standards they set for themselves.",
    author: "Ray Kroc",
    category: "Leadership",
  },
  {
    week_number: 8,
    quote_text: "A good leader takes a little more than his share of the blame, a little less than his share of the credit.",
    author: "Arnold H. Glasow",
    category: "Leadership",
  },
  {
    week_number: 9,
    quote_text: "The art of leadership is saying no, not yes. It is very easy to say yes.",
    author: "Tony Blair",
    category: "Leadership",
  },
  {
    week_number: 10,
    quote_text: "Great leaders are almost always great simplifiers, who can cut through argument, debate and doubt, to offer a solution everybody can understand.",
    author: "Colin Powell",
    category: "Leadership",
  },
  {
    week_number: 11,
    quote_text: "The very essence of leadership is that you have to have a vision. It's got to be a vision you articulate clearly and forcefully on every occasion.",
    author: "Theodore Hesburgh",
    category: "Leadership",
  },
  {
    week_number: 12,
    quote_text: "A leader is a dealer in hope.",
    author: "Napoleon Bonaparte",
    category: "Leadership",
  },
  {
    week_number: 13,
    quote_text: "The role of leadership is to transform the complex situation into small pieces and prioritize them.",
    author: "Carlos Ghosn",
    category: "Leadership",
  },
  {
    week_number: 14,
    quote_text: "The challenge of leadership is to be strong, but not rude; be kind, but not weak; be bold, but not bully; be thoughtful, but not lazy; be humble, but not timid; be proud, but not arrogant; have humor, but without folly.",
    author: "Jim Rohn",
    category: "Leadership",
  },
  {
    week_number: 15,
    quote_text: "Management is doing things right; leadership is doing the right things.",
    author: "Peter Drucker",
    category: "Leadership",
  },
  {
    week_number: 16,
    quote_text: "The supreme quality for leadership is unquestionably integrity. Without it, no real success is possible, no matter whether it is on a section gang, a football field, in an army, or in an office.",
    author: "Dwight D. Eisenhower",
    category: "Leadership",
  },
  {
    week_number: 17,
    quote_text: "A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others.",
    author: "Douglas MacArthur",
    category: "Leadership",
  },
  {
    week_number: 18,
    quote_text: "To handle yourself, use your head; to handle others, use your heart.",
    author: "Eleanor Roosevelt",
    category: "Emotional Intelligence",
  },
  {
    week_number: 19,
    quote_text: "The price of greatness is responsibility.",
    author: "Winston Churchill",
    category: "Leadership",
  },
  {
    week_number: 20,
    quote_text: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.",
    author: "John Quincy Adams",
    category: "Leadership",
  },
  {
    week_number: 21,
    quote_text: "The task of the leader is to get his people from where they are to where they have not been.",
    author: "Henry Kissinger",
    category: "Leadership",
  },
  {
    week_number: 22,
    quote_text: "Leaders think and talk about the solutions. Followers think and talk about the problems.",
    author: "Brian Tracy",
    category: "Leadership",
  },
  {
    week_number: 23,
    quote_text: "Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes.",
    author: "Peter Drucker",
    category: "Leadership",
  },
  {
    week_number: 24,
    quote_text: "Anyone can hold the helm when the sea is calm.",
    author: "Publilius Syrus",
    category: "Resilience",
  },
  {
    week_number: 25,
    quote_text: "A great person attracts great people and knows how to hold them together.",
    author: "Johann Wolfgang von Goethe",
    category: "Team Building",
  },
  {
    week_number: 26,
    quote_text: "The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint enough to keep from meddling with them while they do it.",
    author: "Theodore Roosevelt",
    category: "Leadership",
  },
  {
    week_number: 27,
    quote_text: "I must follow the people. Am I not their leader?",
    author: "Benjamin Disraeli",
    category: "Leadership",
  },
  {
    week_number: 28,
    quote_text: "You don't lead by pointing and telling people some place to go. You lead by going to that place and making a case.",
    author: "Ken Kesey",
    category: "Leadership",
  },
  {
    week_number: 29,
    quote_text: "When the best leader's work is done the people say, 'We did it ourselves.'",
    author: "Lao Tzu",
    category: "Leadership",
  },
  {
    week_number: 30,
    quote_text: "Where there is no vision, the people perish.",
    author: "Proverbs 29:18",
    category: "Leadership",
  },
  {
    week_number: 31,
    quote_text: "I cannot give you the formula for success, but I can give you the formula for failure, which is: Try to please everybody.",
    author: "Herbert Bayard Swope",
    category: "Leadership",
  },
  {
    week_number: 32,
    quote_text: "A man who wants to lead the orchestra must turn his back on the crowd.",
    author: "Max Lucado",
    category: "Leadership",
  },
  {
    week_number: 33,
    quote_text: "What you do has far greater impact than what you say.",
    author: "Stephen Covey",
    category: "Leadership",
  },
  {
    week_number: 34,
    quote_text: "No man will make a great leader who wants to do it all himself, or to get all the credit for doing it.",
    author: "Andrew Carnegie",
    category: "Leadership",
  },
  {
    week_number: 35,
    quote_text: "The most difficult thing is the decision to act, the rest is merely tenacity.",
    author: "Amelia Earhart",
    category: "Motivation",
  },
  {
    week_number: 36,
    quote_text: "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.",
    author: "Alexander the Great",
    category: "Leadership",
  },
  {
    week_number: 37,
    quote_text: "Do not follow where the path may lead. Go instead where there is no path and leave a trail.",
    author: "Ralph Waldo Emerson",
    category: "Innovation",
  },
  {
    week_number: 38,
    quote_text: "Leadership and learning are indispensable to each other.",
    author: "John F. Kennedy",
    category: "Leadership",
  },
  {
    week_number: 39,
    quote_text: "The key to successful leadership today is influence, not authority.",
    author: "Kenneth Blanchard",
    category: "Leadership",
  },
  {
    week_number: 40,
    quote_text: "A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go, but ought to be.",
    author: "Rosalynn Carter",
    category: "Leadership",
  },
  {
    week_number: 41,
    quote_text: "Become the kind of leader that people would follow voluntarily; even if you had no title or position.",
    author: "Brian Tracy",
    category: "Leadership",
  },
  {
    week_number: 42,
    quote_text: "One of the tests of leadership is the ability to recognize a problem before it becomes an emergency.",
    author: "Arnold H. Glasow",
    category: "Leadership",
  },
  {
    week_number: 43,
    quote_text: "Keep your fears to yourself, but share your courage with others.",
    author: "Robert Louis Stevenson",
    category: "Leadership",
  },
  {
    week_number: 44,
    quote_text: "The greatest leaders mobilize others by coalescing people around a shared vision.",
    author: "Ken Blanchard",
    category: "Leadership",
  },
  {
    week_number: 45,
    quote_text: "Leadership is not about being in charge. It is about taking care of those in your charge.",
    author: "Simon Sinek",
    category: "Leadership",
  },
  {
    week_number: 46,
    quote_text: "The task of leadership is not to put greatness into people, but to elicit it, for the greatness is there already.",
    author: "John Buchan",
    category: "Leadership",
  },
  {
    week_number: 47,
    quote_text: "A ruler should be slow to punish and swift to reward.",
    author: "Ovid",
    category: "Leadership",
  },
  {
    week_number: 48,
    quote_text: "He who has never learned to obey cannot be a good commander.",
    author: "Aristotle",
    category: "Leadership",
  },
  {
    week_number: 49,
    quote_text: "The first responsibility of a leader is to define reality. The last is to say thank you. In between, the leader is a servant.",
    author: "Max DePree",
    category: "Leadership",
  },
  {
    week_number: 50,
    quote_text: "A leader's job is not to do the work for others, it's to help others figure out how to do it themselves, to get things done, and to succeed beyond what they thought possible.",
    author: "Simon Sinek",
    category: "Leadership",
  },
  {
    week_number: 51,
    quote_text: "Don't tell people how to do things, tell them what to do and let them surprise you with their results.",
    author: "George S. Patton Jr.",
    category: "Leadership",
  },
  {
    week_number: 52,
    quote_text: "The art of communication is the language of leadership.",
    author: "James Humes",
    category: "Leadership",
  },
];
