import { InspirationQuote } from '@/types';

export const leadershipQuotes: Omit<InspirationQuote, 'id'>[] = [
  {
    week_number: 1,
    quote_text: "A tree is known by its fruit, and a leader by their deeds.",
    author: "African Proverb",
    category: "Leadership",
  },
  {
    week_number: 2,
    quote_text: "A single spark can ignite a fire, and a single idea can transform a nation.",
    author: "African Proverb",
    category: "Innovation",
  },
  {
    week_number: 3,
    quote_text: "The strength of a camel lies in its caravan.",
    author: "African Proverb",
    category: "Community",
  },
  {
    week_number: 4,
    quote_text: "The well that serves many never dries up.",
    author: "African Proverb",
    category: "Community",
  },
  {
    week_number: 5,
    quote_text: "The wise leader plants trees for a shade they may never sit under.",
    author: "African Proverb",
    category: "Legacy",
  },
  {
    week_number: 6,
    quote_text: "He who plants a date palm plants for eternity.",
    author: "African Proverb",
    category: "Legacy",
  },
  {
    week_number: 7,
    quote_text: "A papyrus reed alone is bent by the wind, but bound together, they resist the storm.",
    author: "African Proverb",
    category: "Unity",
  },
  {
    week_number: 8,
    quote_text: "The ink of the scholar is more precious than the blood of the martyr.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 9,
    quote_text: "The Nile may flood, but the pyramids remain.",
    author: "African Proverb",
    category: "Resilience",
  },
  {
    week_number: 10,
    quote_text: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Perseverance",
  },
  {
    week_number: 11,
    quote_text: "The gazelle outpaces the lion, but the caravan reaches the oasis.",
    author: "African Proverb",
    category: "Collaboration",
  },
  {
    week_number: 12,
    quote_text: "The date palm thrives in the desert, reminding us that life blossoms even in adversity.",
    author: "African Proverb",
    category: "Resilience",
  },
  {
    week_number: 13,
    quote_text: "The storyteller knows the past, the poet creates the future.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 14,
    quote_text: "A leader without vision is like a camel without a saddle.",
    author: "African Proverb",
    category: "Vision",
  },
  {
    week_number: 15,
    quote_text: "The sun shines for all, even the lizard in the shade.",
    author: "African Proverb",
    category: "Equity",
  },
  {
    week_number: 16,
    quote_text: "The mountains may crumble, but the stories live on.",
    author: "African Proverb",
    category: "Legacy",
  },
  {
    week_number: 17,
    quote_text: "The argan tree thrives in harsh climates, teaching us to adapt and innovate.",
    author: "African Proverb",
    category: "Innovation",
  },
  {
    week_number: 18,
    quote_text: "The souk thrives on diversity, where many hands build a prosperous market.",
    author: "African Proverb",
    category: "Community",
  },
  {
    week_number: 19,
    quote_text: "A single drop of rain cannot quench a thirst, but many drops fill the river.",
    author: "African Proverb",
    category: "Community",
  },
  {
    week_number: 20,
    quote_text: "The Nile flows north, but the wisdom flows both ways.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 21,
    quote_text: "The desert wind changes the dunes, reminding us that transformation is inevitable.",
    author: "African Proverb",
    category: "Transformation",
  },
  {
    week_number: 22,
    quote_text: "The storyteller's voice echoes across generations, preserving knowledge and identity.",
    author: "African Proverb",
    category: "Legacy",
  },
  {
    week_number: 23,
    quote_text: "The baobab tree endures the seasons, teaching us resilience and patience.",
    author: "African Proverb",
    category: "Resilience",
  },
  {
    week_number: 24,
    quote_text: "The weaver's hands create patterns on the loom, reminding us that unity weaves a strong fabric.",
    author: "African Proverb",
    category: "Unity",
  },
  {
    week_number: 25,
    quote_text: "The olive tree bears fruit year after year, reminding us of patience and long-term vision.",
    author: "African Proverb",
    category: "Patience",
  },
  {
    week_number: 26,
    quote_text: "The desert bloom teaches us that beauty can arise even in unexpected places.",
    author: "African Proverb",
    category: "Resilience",
  },
  {
    week_number: 27,
    quote_text: "The marketplace thrives on bartering, reminding us that collaboration creates mutual benefit.",
    author: "African Proverb",
    category: "Collaboration",
  },
  {
    week_number: 28,
    quote_text: "The ancient walls whisper stories, reminding us of the importance of learning from the past.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 29,
    quote_text: "The eloquent tongue persuades hearts, while the harsh voice repels them.",
    author: "African Proverb",
    category: "Communication",
  },
  {
    week_number: 30,
    quote_text: "The elephant carries a mighty tusk, but the wisdom of the village guides the hunt.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 31,
    quote_text: "The baobab tree shelters all who seek shade, reminding us that leadership serves all.",
    author: "African Proverb",
    category: "Leadership",
  },
  {
    week_number: 32,
    quote_text: "The drumbeat unites the dancers, just as technology can connect the people.",
    author: "African Proverb",
    category: "Unity",
  },
  {
    week_number: 33,
    quote_text: "The river carves its path through the mountains, showing us that transformation can be gradual but powerful.",
    author: "African Proverb",
    category: "Transformation",
  },
  {
    week_number: 34,
    quote_text: "The weaver's hands blend threads into vibrant patterns, reminding us that collaboration creates beauty.",
    author: "African Proverb",
    category: "Collaboration",
  },
  {
    week_number: 35,
    quote_text: "The lion may roar, but the wisdom of the elders guides the pack.",
    author: "African Proverb",
    category: "Wisdom",
  },
  {
    week_number: 36,
    quote_text: "The rain nourishes the seedlings, just as education empowers the young.",
    author: "African Proverb",
    category: "Education",
  },
  {
    week_number: 37,
    quote_text: "The talking drum carries messages across the land, reminding us of the power of communication.",
    author: "African Proverb",
    category: "Communication",
  },
  {
    week_number: 38,
    quote_text: "The blacksmith's hammer transforms iron into tools, reminding us of innovation's potential.",
    author: "African Proverb",
    category: "Innovation",
  },
  {
    week_number: 39,
    quote_text: "The forest thrives in diversity, reminding us that different strengths build a stronger community.",
    author: "African Proverb",
    category: "Community",
  },
  {
    week_number: 40,
    quote_text: "The desert wind shapes the dunes, reminding us that leadership guides change.",
    author: "African Proverb",
    category: "Leadership",
  },
  {
    week_number: 41,
    quote_text: "The well provides life for all, just as education provides opportunity for all.",
    author: "African Proverb",
    category: "Education",
  },
  {
    week_number: 42,
    quote_text: "The griot's songs carry history and wisdom, reminding us of the power of communication.",
    author: "African Proverb",
    category: "Communication",
  },
  {
    week_number: 43,
    quote_text: "The camel traverses vast distances, reminding us that innovation allows us to overcome challenges.",
    author: "African Proverb",
    category: "Innovation",
  },
  {
    week_number: 44,
    quote_text: "The nomadic tribe relies on each other, reminding us that unity is essential for survival.",
    author: "African Proverb",
    category: "Unity",
  },
  {
    week_number: 45,
    quote_text: "The sun warms all, regardless of tribe or village, reminding us that leadership serves all.",
    author: "African Proverb",
    category: "Leadership",
  },
  {
    week_number: 46,
    quote_text: "A camel does not grumble under the weight of its hump.",
    author: "African Proverb",
    category: "Resilience",
  },
];
