export const COUNTRIES_DATA = [
    { name: "Afghanistan", region: "Asia" },
    { name: "Albania", region: "Europe" },
    { name: "Algeria", region: "Africa" },
    { name: "Andorra", region: "Europe" },
    { name: "Angola", region: "Africa" },
    { name: "Antigua and Barbuda", region: "Americas" },
    { name: "Argentina", region: "Americas" },
    { name: "Armenia", region: "Asia" },
    { name: "Australia", region: "Oceania" },
    { name: "Austria", region: "Europe" },
    { name: "Azerbaijan", region: "Asia" },
    { name: "Bahamas", region: "Americas" },
    { name: "Bahrain", region: "Asia" },
    { name: "Bangladesh", region: "Asia" },
    { name: "Barbados", region: "Americas" },
    { name: "Belarus", region: "Europe" },
    { name: "Belgium", region: "Europe" },
    { name: "Belize", region: "Americas" },
    { name: "Benin", region: "Africa" },
    { name: "Bhutan", region: "Asia" },
    { name: "Bolivia", region: "Americas" },
    { name: "Bosnia and Herzegovina", region: "Europe" },
    { name: "Botswana", region: "Africa" },
    { name: "Brazil", region: "Americas" },
    { name: "Brunei", region: "Asia" },
    { name: "Bulgaria", region: "Europe" },
    { name: "Burkina Faso", region: "Africa" },
    { name: "Burundi", region: "Africa" },
    { name: "Cabo Verde", region: "Africa" },
    { name: "Cambodia", region: "Asia" },
    { name: "Cameroon", region: "Africa" },
    { name: "Canada", region: "Americas" },
    { name: "Central African Republic", region: "Africa" },
    { name: "Chad", region: "Africa" },
    { name: "Chile", region: "Americas" },
    { name: "China", region: "Asia" },
    { name: "Colombia", region: "Americas" },
    { name: "Comoros", region: "Africa" },
    { name: "Congo (Congo-Brazzaville)", region: "Africa" },
    { name: "Costa Rica", region: "Americas" },
    { name: "Croatia", region: "Europe" },
    { name: "Cuba", region: "Americas" },
    { name: "Cyprus", region: "Europe" },
    { name: "Czechia (Czech Republic)", region: "Europe" },
    { name: "Democratic Republic of the Congo", region: "Africa" },
    { name: "Denmark", region: "Europe" },
    { name: "Djibouti", region: "Africa" },
    { name: "Dominica", region: "Americas" },
    { name: "Dominican Republic", region: "Americas" },
    { name: "Ecuador", region: "Americas" },
    { name: "Egypt", region: "Africa" },
    { name: "El Salvador", region: "Americas" },
    { name: "Equatorial Guinea", region: "Africa" },
    { name: "Eritrea", region: "Africa" },
    { name: "Estonia", region: "Europe" },
    { name: "Eswatini (fmr. Swaziland)", region: "Africa" },
    { name: "Ethiopia", region: "Africa" },
    { name: "Fiji", region: "Oceania" },
    { name: "Finland", region: "Europe" },
    { name: "France", region: "Europe" },
    { name: "Gabon", region: "Africa" },
    { name: "Gambia", region: "Africa" },
    { name: "Georgia", region: "Asia" },
    { name: "Germany", region: "Europe" },
    { name: "Ghana", region: "Africa" },
    { name: "Greece", region: "Europe" },
    { name: "Grenada", region: "Americas" },
    { name: "Guatemala", region: "Americas" },
    { name: "Guinea", region: "Africa" },
    { name: "Guinea-Bissau", region: "Africa" },
    { name: "Guyana", region: "Americas" },
    { name: "Haiti", region: "Americas" },
    { name: "Honduras", region: "Americas" },
    { name: "Hungary", region: "Europe" },
    { name: "Iceland", region: "Europe" },
    { name: "India", region: "Asia" },
    { name: "Indonesia", region: "Asia" },
    { name: "Iran", region: "Asia" },
    { name: "Iraq", region: "Asia" },
    { name: "Ireland", region: "Europe" },
    { name: "Israel", region: "Asia" },
    { name: "Italy", region: "Europe" },
    { name: "Jamaica", region: "Americas" },
    { name: "Japan", region: "Asia" },
    { name: "Jordan", region: "Asia" },
    { name: "Kazakhstan", region: "Asia" },
    { name: "Kenya", region: "Africa" },
    { name: "Kiribati", region: "Oceania" },
    { name: "Kuwait", region: "Asia" },
    { name: "Kyrgyzstan", region: "Asia" },
    { name: "Laos", region: "Asia" },
    { name: "Latvia", region: "Europe" },
    { name: "Lebanon", region: "Asia" },
    { name: "Lesotho", region: "Africa" },
    { name: "Liberia", region: "Africa" },
    { name: "Libya", region: "Africa" },
    { name: "Liechtenstein", region: "Europe" },
    { name: "Lithuania", region: "Europe" },
    { name: "Luxembourg", region: "Europe" },
    { name: "Madagascar", region: "Africa" },
    { name: "Malawi", region: "Africa" },
    { name: "Malaysia", region: "Asia" },
    { name: "Maldives", region: "Asia" },
    { name: "Mali", region: "Africa" },
    { name: "Malta", region: "Europe" },
    { name: "Marshall Islands", region: "Oceania" },
    { name: "Mauritania", region: "Africa" },
    { name: "Mauritius", region: "Africa" },
    { name: "Mexico", region: "Americas" },
    { name: "Micronesia", region: "Oceania" },
    { name: "Moldova", region: "Europe" },
    { name: "Monaco", region: "Europe" },
    { name: "Mongolia", region: "Asia" },
    { name: "Montenegro", region: "Europe" },
    { name: "Morocco", region: "Africa" },
    { name: "Mozambique", region: "Africa" },
    { name: "Myanmar (formerly Burma)", region: "Asia" },
    { name: "Namibia", region: "Africa" },
    { name: "Nauru", region: "Oceania" },
    { name: "Nepal", region: "Asia" },
    { name: "Netherlands", region: "Europe" },
    { name: "New Zealand", region: "Oceania" },
    { name: "Nicaragua", region: "Americas" },
    { name: "Niger", region: "Africa" },
    { name: "Nigeria", region: "Africa" },
    { name: "North Korea", region: "Asia" },
    { name: "North Macedonia", region: "Europe" },
    { name: "Norway", region: "Europe" },
    { name: "Oman", region: "Asia" },
    { name: "Pakistan", region: "Asia" },
    { name: "Palau", region: "Oceania" },
    { name: "Palestine State", region: "Asia" },
    { name: "Panama", region: "Americas" },
    { name: "Papua New Guinea", region: "Oceania" },
    { name: "Paraguay", region: "Americas" },
    { name: "Peru", region: "Americas" },
    { name: "Philippines", region: "Asia" },
    { name: "Poland", region: "Europe" },
    { name: "Portugal", region: "Europe" },
    { name: "Qatar", region: "Asia" },
    { name: "Romania", region: "Europe" },
    { name: "Russia", region: "Europe" },
    { name: "Rwanda", region: "Africa" },
    { name: "Saint Kitts and Nevis", region: "Americas" },
    { name: "Saint Lucia", region: "Americas" },
    { name: "Saint Vincent and the Grenadines", region: "Americas" },
    { name: "Samoa", region: "Oceania" },
    { name: "San Marino", region: "Europe" },
    { name: "Sao Tome and Principe", region: "Africa" },
    { name: "Saudi Arabia", region: "Asia" },
    { name: "Senegal", region: "Africa" },
    { name: "Serbia", region: "Europe" },
    { name: "Seychelles", region: "Africa" },
    { name: "Sierra Leone", region: "Africa" },
    { name: "Singapore", region: "Asia" },
    { name: "Slovakia", region: "Europe" },
    { name: "Slovenia", region: "Europe" },
    { name: "Solomon Islands", region: "Oceania" },
    { name: "Somalia", region: "Africa" },
    { name: "South Africa", region: "Africa" },
    { name: "South Korea", region: "Asia" },
    { name: "South Sudan", region: "Africa" },
    { name: "Spain", region: "Europe" },
    { name: "Sri Lanka", region: "Asia" },
    { name: "Sudan", region: "Africa" },
    { name: "Suriname", region: "Americas" },
    { name: "Sweden", region: "Europe" },
    { name: "Switzerland", region: "Europe" },
    { name: "Syria", region: "Asia" },
    { name: "Taiwan", region: "Asia" },
    { name: "Tajikistan", region: "Asia" },
    { name: "Tanzania", region: "Africa" },
    { name: "Thailand", region: "Asia" },
    { name: "Timor-Leste", region: "Asia" },
    { name: "Togo", region: "Africa" },
    { name: "Tonga", region: "Oceania" },
    { name: "Trinidad and Tobago", region: "Americas" },
    { name: "Tunisia", region: "Africa" },
    { name: "Turkey", region: "Asia" },
    { name: "Turkmenistan", region: "Asia" },
    { name: "Tuvalu", region: "Oceania" },
    { name: "Uganda", region: "Africa" },
    { name: "Ukraine", region: "Europe" },
    { name: "United Arab Emirates", region: "Asia" },
    { name: "United Kingdom", region: "Europe" },
    { name: "United States", region: "Americas" },
    { name: "Uruguay", region: "Americas" },
    { name: "Uzbekistan", region: "Asia" },
    { name: "Vanuatu", region: "Oceania" },
    { name: "Vatican City", region: "Europe" },
    { name: "Venezuela", region: "Americas" },
    { name: "Vietnam", region: "Asia" },
    { name: "Yemen", region: "Asia" },
    { name: "Zambia", region: "Africa" },
    { name: "Zimbabwe", region: "Africa" },
];
