/**
 * Course Pre/Post SurveyMonkey catalog.
 *
 * AUTO-GENERATED by `npm run sync:course-surveys` — do not hand-edit the list.
 * Re-run the sync after creating/renaming surveys in SurveyMonkey.
 *
 * Generated: 2026-08-11T13:33:09.406Z
 * Source: SurveyMonkey API (/v3/surveys + collectors)
 */

export type CourseSurveyKind = 'pre' | 'post'

export interface CourseSurveyLink {
  /** SurveyMonkey survey id. */
  surveyId?: string
  /** Human survey title from SurveyMonkey (used for API matching). */
  surveyTitle: string
  kind: CourseSurveyKind
  /** Course title fragment(s) used to match a T4L course. */
  courseMatchers: string[]
  /** SurveyMonkey web collector URL. */
  collectorUrl: string
}

/**
 * Full Pre/Post catalog synced from SurveyMonkey.
 * Only rows with an open (or available) weblink collector URL are included.
 */
export const COURSE_SURVEY_LINKS: CourseSurveyLink[] = [
  {
    surveyId: '521460429',
    surveyTitle: '🎓Pre-Onboarding Assessment',
    kind: 'pre',
    courseMatchers: [
      '🎓pre onboarding',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/5M5MDCP',
  },
  {
    surveyId: '422324683',
    surveyTitle: 'AI for Transformation Leaders: Judgement Over Features - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'ai judgement over features',
      'ai judgement',
      'ai judgement over',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/S5PCWBB',
  },
  {
    surveyId: '526504910',
    surveyTitle: 'AI for Transformation Leaders: Judgment Over Features - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'ai judgment over features',
      'ai judgment',
      'ai judgment over',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TBXZ98R',
  },
  {
    surveyId: '527319613',
    surveyTitle: 'AI for Transformation Leaders: Judgment Over Features - Pre-Course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'ai judgment over features (external rater)',
      'ai judgment',
      'ai judgment over',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVXMVTJ',
  },
  {
    surveyId: '421467267',
    surveyTitle: 'Art of Connection - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'art of connection',
      'art of',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/YFQLRHT',
  },
  {
    surveyId: '526426698',
    surveyTitle: 'Authority and Presence in High-Stakes Transformation - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'authority and presence in high stakes transformation',
      'authority and',
      'authority and presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/KXG3Y3F',
  },
  {
    surveyId: '422369068',
    surveyTitle: 'Authority and Presence in High-Stakes Transformation pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'authority and presence in high stakes transformation (external rater)',
      'authority and',
      'authority and presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HF6FX5G',
  },
  {
    surveyId: '526423240',
    surveyTitle: 'Building Teams That Survive Transformation - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'building teams that survive transformation',
      'building teams',
      'building teams that',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/5ZSJJ2G',
  },
  {
    surveyId: '422368129',
    surveyTitle: 'Building Teams That Survive Transformation pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'building teams that survive transformation (external rater)',
      'building teams',
      'building teams that',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/H3VWN96',
  },
  {
    surveyId: '421472098',
    surveyTitle: 'Career Acceleration for Transformation Practitioners - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'career acceleration for transformation practitioners',
      'career acceleration',
      'career acceleration for',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/268BPJ9',
  },
  {
    surveyId: '422368886',
    surveyTitle: 'Career Acceleration for Transformation Practitioners pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'career acceleration for transformation practitioners (external rater)',
      'career acceleration',
      'career acceleration for',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/H3KQNPW',
  },
  {
    surveyId: '421470473',
    surveyTitle: 'Data-Driven Decisions in Digital Transformation - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'data driven decisions in digital transformation',
      'data driven',
      'data driven decisions',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/2Q3RGBL',
  },
  {
    surveyId: '527319542',
    surveyTitle: 'Data-Driven Decisions in Digital Transformation - Pre-Course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'data driven decisions in digital transformation (external rater)',
      'data driven',
      'data driven decisions',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/JGNFD6W',
  },
  {
    surveyId: '421473661',
    surveyTitle: 'Delivering Transformation: Project Leadership That Sticks - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'delivering transformation project leadership that sticks',
      'delivering transformation',
      'delivering transformation project',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/26CCLLN',
  },
  {
    surveyId: '527210517',
    surveyTitle: 'Delivering Transformation: Project Leadership That Sticks - Pre-Course Assessment(External Rater)',
    kind: 'pre',
    courseMatchers: [
      'delivering transformation project leadership that sticks (external rater)',
      'delivering transformation',
      'delivering transformation project',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TFPG5GZ',
  },
  {
    surveyId: '526425895',
    surveyTitle: 'Digital Bias: The Risk Your Transformation Isn\'t Measuring - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'digital bias the risk transformation isn\'t measuring',
      'digital bias',
      'digital bias the',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/KXYH7PR',
  },
  {
    surveyId: '422369041',
    surveyTitle: 'Digital Bias: The Risk Your Transformation Isn\'t Measuring pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'digital bias the risk transformation isn\'t measuring (external rater)',
      'digital bias',
      'digital bias the',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HF5V682',
  },
  {
    surveyId: '422325360',
    surveyTitle: 'Digital Transformation & Data - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'digital transformation & data',
      'digital transformation',
      'digital transformation &',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RLGBQY7',
  },
  {
    surveyId: '422368091',
    surveyTitle: 'Digital Transformation with Data Sentinels - Pre-Course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'digital transformation with data sentinels (external rater)',
      'digital transformation',
      'digital transformation with',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/H3D7FLM',
  },
  {
    surveyId: '527277207',
    surveyTitle: 'Foundations of Leadership and Team Dynamics - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'foundations of leadership and team dynamics',
      'foundations of',
      'foundations of leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8FHB5W8',
  },
  {
    surveyId: '421470985',
    surveyTitle: 'From Strategy to Execution in Transformation Programmes - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'from strategy to execution in transformation programmes',
      'from strategy',
      'from strategy to',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/2W9G53F',
  },
  {
    surveyId: '422368614',
    surveyTitle: 'From Strategy to Execution in Transformation Programmes pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'from strategy to execution in transformation programmes (external rater)',
      'from strategy',
      'from strategy to',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HT7NLBR',
  },
  {
    surveyId: '422326687',
    surveyTitle: 'Hire Me Already - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'hire me already',
      'hire me',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RJPXYSK',
  },
  {
    surveyId: '421526274',
    surveyTitle: 'Know Your Leadership Pattern Under Pressure - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'know leadership pattern under pressure',
      'know leadership',
      'know leadership pattern',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/FDG8HSP',
  },
  {
    surveyId: '527320853',
    surveyTitle: 'Know Your Leadership Pattern Under Pressure pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'know leadership pattern under pressure (external rater)',
      'know leadership',
      'know leadership pattern',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QLZT6JX',
  },
  {
    surveyId: '422326880',
    surveyTitle: 'Leading Through Change - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'leading through change',
      'leading through',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RQPLR3M',
  },
  {
    surveyId: '526505997',
    surveyTitle: 'Leading Transformation Across Cultures and Borders - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'leading transformation across cultures and borders',
      'leading transformation',
      'leading transformation across',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TZHS6LN',
  },
  {
    surveyId: '527319689',
    surveyTitle: 'Leading Transformation Across Cultures and Borders - Pre-Course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'leading transformation across cultures and borders (external rater)',
      'leading transformation',
      'leading transformation across',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVNDKWZ',
  },
  {
    surveyId: '422368820',
    surveyTitle: 'Leading Under Pressure: The Transformation Leader\'s Operating System pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'leading under pressure the transformation leader\'s operating system (external rater)',
      'leading under',
      'leading under pressure',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HFMWD35',
  },
  {
    surveyId: '527278756',
    surveyTitle: 'Leading under Pressure: The Transformation Leader\'s Operating System- Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'leading under pressure the transformation leader\'s operating system',
      'leading under',
      'leading under pressure',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/LK58ZYH',
  },
  {
    surveyId: '527320269',
    surveyTitle: 'Navigating Organisational Resistance in Transformation pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'navigating organisational resistance in transformation (external rater)',
      'navigating organisational',
      'navigating organisational resistance',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVS6Y2C',
  },
  {
    surveyId: '526423329',
    surveyTitle: 'Navigating Organizational Resistance in Transformation - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'navigating organizational resistance in transformation',
      'navigating organizational',
      'navigating organizational resistance',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/5Z5MQX3',
  },
  {
    surveyId: '527219926',
    surveyTitle: 'Project Management for Leaders - Pre-Course Assessment(External Rater) - T1',
    kind: 'pre',
    courseMatchers: [
      'project management for leaders (external rater) t1',
      'project management',
      'project management for',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/XFGRKJJ',
  },
  {
    surveyId: '527320748',
    surveyTitle: 'Resilience Under Sustained Transformation Pressure pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'resilience under sustained transformation pressure (external rater)',
      'resilience under',
      'resilience under sustained',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVD3KKN',
  },
  {
    surveyId: '422368983',
    surveyTitle: 'Stakeholder Influence for Transformation Leaders pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'stakeholder influence (external rater)',
      'stakeholder influence',
      'stakeholder influence (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HF5WHRL',
  },
  {
    surveyId: '526426778',
    surveyTitle: 'The Leader Your Transformation Team Actually Needs - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'the leader transformation team actually needs',
      'the leader',
      'the leader transformation',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/KFDZ7N8',
  },
  {
    surveyId: '527320806',
    surveyTitle: 'The Leader Your Transformation Team Actually Needs pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'the leader transformation team actually needs (external rater)',
      'the leader',
      'the leader transformation',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVKZ5BR',
  },
  {
    surveyId: '526426737',
    surveyTitle: 'The Resilience Under Sustained Transformation Pressure - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'the resilience under sustained transformation pressure',
      'the resilience',
      'the resilience under',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/KNLCB86',
  },
  {
    surveyId: '422327196',
    surveyTitle: 'The Stakeholder Influence for Transformation Leaders -Pre-course assessment',
    kind: 'pre',
    courseMatchers: [
      'the stakeholder influence',
      'the stakeholder',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RR7V52V',
  },
  {
    surveyId: '526427007',
    surveyTitle: 'Think Like an Owner - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'think like an owner',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/KFM9TPH',
  },
  {
    surveyId: '422260189',
    surveyTitle: 'Think Like an Owner - Pre-Course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'think like an owner (external rater)',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/562S88T',
  },
  {
    surveyId: '422268836',
    surveyTitle: 'Think Like an Owner - Pre-Course Assessment(External Rater) - T1',
    kind: 'pre',
    courseMatchers: [
      'think like an owner (external rater) t1',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8BZDT3L',
  },
  {
    surveyId: '422369275',
    surveyTitle: 'Think Like an Owner pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'think like an owner (external rater)',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/HFRF8DN',
  },
  {
    surveyId: '421498236',
    surveyTitle: 'Transformational Leadership - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'transformational leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/SZV2QF5',
  },
  {
    surveyId: '421553486',
    surveyTitle: 'Transformational Leadership - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'transformational leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/PML7Q62',
  },
  {
    surveyId: '527320925',
    surveyTitle: 'Transformational Leadership pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'transformational leadership (external rater)',
      'transformational leadership',
      'transformational leadership (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QLP7BZ3',
  },
  {
    surveyId: '527279390',
    surveyTitle: 'Unlocking Your Leadership Potential-Pre course assessment: A Free Guide to Transformational Leadership',
    kind: 'pre',
    courseMatchers: [
      'unlocking leadership potential a free guide to transformational leadership',
      'unlocking leadership',
      'unlocking leadership potential',
      'transformational leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/L9DDJM6',
  },
  {
    surveyId: '526478691',
    surveyTitle: 'Your Digital Presence as a Transformation Leader - Pre-Course Assessment',
    kind: 'pre',
    courseMatchers: [
      'digital presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/JXT9NH9',
  },
  {
    surveyId: '527320355',
    surveyTitle: 'Your Digital Presence as a Transformation Leader pre-course Assessment (External Rater)',
    kind: 'pre',
    courseMatchers: [
      'digital presence (external rater)',
      'digital presence',
      'digital presence (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QVWXSS9',
  },
  {
    surveyId: '526505110',
    surveyTitle: 'AI for Transformation Leaders: Judgment Over Features - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'ai judgment over features',
      'ai judgment',
      'ai judgment over',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TH2XWGS',
  },
  {
    surveyId: '422442238',
    surveyTitle: 'AI for Transformation Leaders: Judgment Over Features - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'ai judgment over features (external rater)',
      'ai judgment',
      'ai judgment over',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QJTC9YW',
  },
  {
    surveyId: '526531769',
    surveyTitle: 'Authority and Presence in High-Stakes Transformation - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'authority and presence in high stakes transformation',
      'authority and',
      'authority and presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/338R23N',
  },
  {
    surveyId: '422442318',
    surveyTitle: 'Authority and Presence in High-Stakes Transformation post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'authority and presence in high stakes transformation (external rater)',
      'authority and',
      'authority and presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QJGQVZJ',
  },
  {
    surveyId: '526507018',
    surveyTitle: 'Building Teams That Survive Transformation - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'building teams that survive transformation',
      'building teams',
      'building teams that',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/MDRKJ3Y',
  },
  {
    surveyId: '422456727',
    surveyTitle: 'Building Teams That Survive Transformation post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'building teams that survive transformation (external rater)',
      'building teams',
      'building teams that',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RSGVJT8',
  },
  {
    surveyId: '526531536',
    surveyTitle: 'Career Acceleration for Transformation Practitioners - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'career acceleration for transformation practitioners',
      'career acceleration',
      'career acceleration for',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FWQG2X',
  },
  {
    surveyId: '527408678',
    surveyTitle: 'Career Acceleration for Transformation Practitioners post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'career acceleration for transformation practitioners (external rater)',
      'career acceleration',
      'career acceleration for',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/89QD2L5',
  },
  {
    surveyId: '421554137',
    surveyTitle: 'Data-Driven Decisions in Digital Transformation - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'data driven decisions in digital transformation',
      'data driven',
      'data driven decisions',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/PFLNCFV',
  },
  {
    surveyId: '422456802',
    surveyTitle: 'Data-Driven Decisions in Digital Transformation - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'data driven decisions in digital transformation (external rater)',
      'data driven',
      'data driven decisions',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RRCP5R2',
  },
  {
    surveyId: '526531595',
    surveyTitle: 'Delivering Transformation: Project Leadership That Sticks - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'delivering transformation project leadership that sticks',
      'delivering transformation',
      'delivering transformation project',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FMM8DH',
  },
  {
    surveyId: '422260382',
    surveyTitle: 'Delivering Transformation: Project Leadership That Sticks - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'delivering transformation project leadership that sticks (external rater)',
      'delivering transformation',
      'delivering transformation project',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/5ZHV9KW',
  },
  {
    surveyId: '526531710',
    surveyTitle: 'Digital Bias: The Risk Your Transformation Isn\'t Measuring - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'digital bias the risk transformation isn\'t measuring',
      'digital bias',
      'digital bias the',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FPQ9WL',
  },
  {
    surveyId: '527408442',
    surveyTitle: 'Digital Bias: The Risk Your Transformation Isn\'t Measuring post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'digital bias the risk transformation isn\'t measuring (external rater)',
      'digital bias',
      'digital bias the',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/877P3KR',
  },
  {
    surveyId: '526506574',
    surveyTitle: 'Digital Transformation & Data - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'digital transformation & data',
      'digital transformation',
      'digital transformation &',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/ML83HLX',
  },
  {
    surveyId: '527408491',
    surveyTitle: 'Digital Transformation with Data Sentinels - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'digital transformation with data sentinels (external rater)',
      'digital transformation',
      'digital transformation with',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/87WPCW7',
  },
  {
    surveyId: '526507558',
    surveyTitle: 'From Strategy to Execution in Transformation - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'from strategy to execution in transformation',
      'from strategy',
      'from strategy to',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/MTFNQ5Z',
  },
  {
    surveyId: '527408521',
    surveyTitle: 'From Strategy to Execution in Transformation Programmes post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'from strategy to execution in transformation programmes (external rater)',
      'from strategy',
      'from strategy to',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/87X5W33',
  },
  {
    surveyId: '526509410',
    surveyTitle: 'Hire Me Already - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'hire me already',
      'hire me',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/MXGBQLZ',
  },
  {
    surveyId: '526531963',
    surveyTitle: 'Know Your Leadership Pattern Under Pressure - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'know leadership pattern under pressure',
      'know leadership',
      'know leadership pattern',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/33ZMSMC',
  },
  {
    surveyId: '422442341',
    surveyTitle: 'Know Your Leadership Pattern Under Pressure post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'know leadership pattern under pressure (external rater)',
      'know leadership',
      'know leadership pattern',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QJZCBKT',
  },
  {
    surveyId: '421566574',
    surveyTitle: 'Leading Through Change - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'leading through change',
      'leading through',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8CF5WSY',
  },
  {
    surveyId: '526505855',
    surveyTitle: 'Leading Transformation Across Cultures and Borders - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'leading transformation across cultures and borders',
      'leading transformation',
      'leading transformation across',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TZNP9SY',
  },
  {
    surveyId: '422456626',
    surveyTitle: 'Leading Transformation Across Cultures and Borders - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'leading transformation across cultures and borders (external rater)',
      'leading transformation',
      'leading transformation across',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RSSZVYJ',
  },
  {
    surveyId: '526531483',
    surveyTitle: 'Leading Under Pressure- Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'leading under pressure',
      'leading under',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FDHD2P',
  },
  {
    surveyId: '527408561',
    surveyTitle: 'Navigating Organisational Resistance in Transformation post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'navigating organisational resistance in transformation (external rater)',
      'navigating organisational',
      'navigating organisational resistance',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/87H3WZP',
  },
  {
    surveyId: '526518469',
    surveyTitle: 'Navigating Organizational Resistance in Transformation - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'navigating organizational resistance in transformation',
      'navigating organizational',
      'navigating organizational resistance',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/NJGTFPB',
  },
  {
    surveyId: '421579747',
    surveyTitle: 'Resilience Under Sustained Transformation Pressure - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'resilience under sustained transformation pressure',
      'resilience under',
      'resilience under sustained',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8QD7735',
  },
  {
    surveyId: '422442367',
    surveyTitle: 'Resilience Under Sustained Transformation Pressure post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'resilience under sustained transformation pressure (external rater)',
      'resilience under',
      'resilience under sustained',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QQK6CNH',
  },
  {
    surveyId: '422456433',
    surveyTitle: 'Stakeholder Influence for Transformation Leaders post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'stakeholder influence (external rater)',
      'stakeholder influence',
      'stakeholder influence (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RQGDKXT',
  },
  {
    surveyId: '421579810',
    surveyTitle: 'The Leader Your Transformation Team Actually Needs - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'the leader transformation team actually needs',
      'the leader',
      'the leader transformation',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8QWPKCS',
  },
  {
    surveyId: '422442395',
    surveyTitle: 'The Leader Your Transformation Team Actually Needs post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'the leader transformation team actually needs (external rater)',
      'the leader',
      'the leader transformation',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/QQ9FRRX',
  },
  {
    surveyId: '526531653',
    surveyTitle: 'The Stakeholder Influence for Transformation Leaders -Post-course assessment',
    kind: 'post',
    courseMatchers: [
      'the stakeholder influence',
      'the stakeholder',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FXHH85',
  },
  {
    surveyId: '526531927',
    surveyTitle: 'Think Like an Owner - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'think like an owner',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/333HSJ9',
  },
  {
    surveyId: '527211804',
    surveyTitle: 'Think Like an Owner - Post-Course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'think like an owner (external rater)',
      'think like',
      'think like an',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/TZFCX7X',
  },
  {
    surveyId: '421552682',
    surveyTitle: 'Transformational Leadership - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'transformational leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/PTYZG7F',
  },
  {
    surveyId: '422457070',
    surveyTitle: 'Transformational Leadership post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'transformational leadership (external rater)',
      'transformational leadership',
      'transformational leadership (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RT5LFVS',
  },
  {
    surveyId: '421579852',
    surveyTitle: 'Unlocking Your Leadership Potential-Post course assessment: A Free Guide to Transformational Leadership',
    kind: 'post',
    courseMatchers: [
      'unlocking leadership potential a free guide to transformational leadership',
      'unlocking leadership',
      'unlocking leadership potential',
      'transformational leadership',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/8QMJQJV',
  },
  {
    surveyId: '526531434',
    surveyTitle: 'Your Digital Presence as a Transformation Leader - Post-Course Assessment',
    kind: 'post',
    courseMatchers: [
      'digital presence',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/3FV7J8H',
  },
  {
    surveyId: '422457094',
    surveyTitle: 'Your Digital Presence as a Transformation Leader post-course Assessment (External Rater)',
    kind: 'post',
    courseMatchers: [
      'digital presence (external rater)',
      'digital presence',
      'digital presence (external',
    ],
    collectorUrl: 'https://www.surveymonkey.com/r/RM7JYNW',
  },
]

/** Legacy fallback used when no course-specific pre survey is configured. */
export const DEFAULT_PRE_COURSE_SURVEY_URL = 'https://www.surveymonkey.com/r/KFM9TPH'

const normalize = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()

const isExternalRater = (row: CourseSurveyLink): boolean =>
  /external\s*rater/i.test(row.surveyTitle)

export const findCourseSurvey = (
  courseTitle: string | null | undefined,
  kind: CourseSurveyKind,
  options?: { includeExternalRater?: boolean },
): CourseSurveyLink | null => {
  if (!courseTitle?.trim()) return null
  const haystack = normalize(courseTitle)
  const includeExternal = Boolean(options?.includeExternalRater)
  const candidates = COURSE_SURVEY_LINKS.filter((row) => {
    if (row.kind !== kind) return false
    if (!includeExternal && isExternalRater(row)) return false
    return true
  })

  // Prefer the longest matcher hit so "digital presence" beats a generic word.
  let best: CourseSurveyLink | null = null
  let bestLen = 0
  for (const row of candidates) {
    for (const matcher of row.courseMatchers) {
      const needle = normalize(matcher)
      if (!needle) continue
      if (haystack.includes(needle) && needle.length > bestLen) {
        best = row
        bestLen = needle.length
      }
    }
  }
  return best
}

export const listCourseSurveys = (kind?: CourseSurveyKind): CourseSurveyLink[] =>
  kind ? COURSE_SURVEY_LINKS.filter((row) => row.kind === kind) : [...COURSE_SURVEY_LINKS]

export const resolvePreCourseSurveyUrl = (courseTitle?: string | null): string =>
  findCourseSurvey(courseTitle, 'pre')?.collectorUrl ?? DEFAULT_PRE_COURSE_SURVEY_URL

export const resolvePostCourseSurveyUrl = (courseTitle?: string | null): string | null =>
  findCourseSurvey(courseTitle, 'post')?.collectorUrl ?? null
